import streamlit as st
import time
from agents.researcher import run_researcher_agent
from agents.summariser import run_summariser_agent


st.title('AI Summary Assistant 🔎')

topic = st.text_input("Enter a topic that you would like to search: ")

if st.button("Generate results") and topic:
    try:
        with st.spinner("Generating Results"):
            research_output = run_researcher_agent(topic)
            summarise_output = run_summariser_agent(research_output)

            # st.markdown("### ✍️ Summarised Findings")
            st.markdown("")
            st.markdown(summarise_output)

            st.markdown("")
            st.info("⚠️ This summary is generated by AI and may not be accurate. Please always verify sources")

            st.markdown("")
            
        with st.expander("🔍 View Raw Research Results"):
            st.markdown(research_output)
         
       
        st.caption("🧠 Powered by Mistral-7B via OpenRouter.ai")

        
        time.sleep(2)


    except Exception as e:
        st.error("Oops, something went wrong. Please try again.")


